#!/usr/bin/env python

from sys import argv
from click import secho
from  pykachu import interpreter, utils

def main():
	if len(argv) < 2:
		utils.pika_print('No Pika file specified')
		return
	
	
	file = argv[1]
	if len(argv) > 2:
		try:
			args = [int(arg) for arg in argv[2:]]
		except ValueError:
			utils.pika_print('Invalid input, please provide exclusively integers')
	else:
		args = []
	interpreter.run(file, args)

if __name__ == '__main__':
	main()
	print ''
