#!/usr/bin/env python

import click
from pykachu import interpreter, utils


@click.command()
@click.argument('filename')
@click.argument('args_', nargs=-1)
@click.option('-d', '-D', '--debug', is_flag=True)
def main(filename=None, args_=[], debug=False):
    if not filename:
        utils.pika_print('No Pika file specified')
        return
    if len(args_) > 0:
        try:
            args_ = [int(arg) for arg in args_]
        except ValueError:
            utils.pika_print('Invalid input, please provide exclusively integers')
    else:
        args_ = []
    interpreter.run(filename, args_, debug)


if __name__ == '__main__':
    main()
    print ''
